import React from 'react';
// eslint-disable-next-line
import { ShieldCheck, Mail, Building, FileText, HelpCircle } from 'lucide-react';

const InfoPage = ({ infoType }) => {
  const renderContent = () => {
    switch (infoType) {
      case 'about':
        return (
          <div>
            <h2 style={styles.title}>About AbKharido.com</h2>
            <p style={styles.paragraph}>
              Welcome to <strong>AbKharido.com</strong>, India's premier direct-to-consumer e-commerce marketplace. 
              Established in 2026, we specialize in high-quality consumer electronics, home appliances, footwear, 
              and apparel shipped directly from fulfillment centers.
            </p>
            <h3 style={styles.subtitle}>Our Direct Sales Promise</h3>
            <p style={styles.paragraph}>
              Unlike other platforms, we do not host unverified third-party sellers. Every item listed on 
              AbKharido.com is owned, cataloged, warehoused, and directly dispatched by our team. This guarantees 
              genuine brand warranty, strict packaging standards, and quick support resolutions.
            </p>
            <h3 style={styles.subtitle}>Referral & Sharing Program</h3>
            <p style={styles.paragraph}>
              We believe in rewarding our community. Shoppers earn shopping discount coins, while creators/influencers 
              receive withdrawable cash commissions on sales made through secure tracking links.
            </p>
            
            <h3 style={styles.subtitle}>💼 Careers</h3>
            <p style={styles.paragraph}>
              We are constantly seeking smart minds in warehouse operations, customer service, supply logistics, and 
              software engineering. If you would like to join our self-operated e-commerce crew, please drop your resume 
              at <a href="mailto:careers@abkharido.com" style={{ color: 'var(--primary-color)', fontWeight: 'bold' }}>careers@abkharido.com</a>.
            </p>

            <h3 style={styles.subtitle}>📦 Wholesale Enquiries</h3>
            <p style={styles.paragraph}>
              Are you looking to buy wholesale stocks, corporate gifts, or place bulk institutional orders? Get custom discounted pricing quotes by contacting our bulk channel desk at <strong>wholesale@abkharido.com</strong>.
            </p>
          </div>
        );
      case 'terms':
        return (
          <div>
            <h2 style={styles.title}>Terms of Use & Guidelines</h2>
            <p style={styles.date}>Last Updated: July 2026</p>
            <p style={styles.paragraph}>
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there 
              under as applicable. This electronic record is generated by a computer system and does not require 
              any physical or digital signatures.
            </p>
            <h3 style={styles.subtitle}>1. Platform Account Security</h3>
            <p style={styles.paragraph}>
              Registration and login on AbKharido.com is protected via secure One-Time Password (OTP) verification. 
              Users are responsible for maintaining the privacy of their OTP sessions and are advised against 
              exposing registration keys.
            </p>
            <h3 style={styles.subtitle}>2. Payment Terms & Refunds</h3>
            <p style={styles.paragraph}>
              All transactions are processed through our partner payment gateways (Cashfree Payments). 
              Funds are held securely and orders are dispatched once payment status is verified. Refund processing 
              usually takes 5-7 business days to be credited back to your original payment method.
            </p>
            <h3 style={styles.subtitle}>3. Affiliate Partnerships Guidelines</h3>
            <p style={styles.paragraph}>
              Affiliates and creators are required to share links responsibly. Spamming social channels, utilizing 
              automated traffic bots, or making false advertising claims is strictly prohibited and will lead to instant 
              commission ledger termination.
            </p>
          </div>
        );
      case 'privacy':
        return (
          <div>
            <h2 style={styles.title}>Privacy Policy</h2>
            <p style={styles.date}>Last Updated: July 2026</p>
            <p style={styles.paragraph}>
              We value the trust you place in us. That's why we insist upon the highest standards for secure 
              transactions and customer information privacy. Please read the following statement to learn 
              about our information gathering and dissemination practices.
            </p>
            <h3 style={styles.subtitle}>1. Collection of Information</h3>
            <p style={styles.paragraph}>
              We collect user emails, shipping addresses, and mobile numbers for verification and order fulfillment. 
              We do NOT store credit card details, netbanking passwords, or UPI pins. All transaction screens 
              are securely operated by Cashfree Payments Web SDK.
            </p>
            <h3 style={styles.subtitle}>2. Tracking Links & Cookies</h3>
            <p style={styles.paragraph}>
              Our referral sharing program utilizes anonymous random codes (e.g. <code>REF-XXXXX</code>) to log 
              conversions. Personal details are never exposed in URLs or sharing buttons.
            </p>
          </div>
        );
      case 'returns':
        return (
          <div>
            <h2 style={styles.title}>Cancellation, Returns & Shipping</h2>
            <p style={styles.paragraph}>
              We want you to be fully satisfied with every purchase. AbKharido offers a user-friendly cancellation 
              and returns policy.
            </p>
            <h3 style={styles.subtitle}>7-Day Replacement Guarantee</h3>
            <p style={styles.paragraph}>
              All direct stock electronics, mobiles, and fashion items are covered by a <strong>7-Day Replacement 
              Guarantee</strong>. If your item arrives damaged, defective, or different from described, you can request 
              a replacement from your Orders panel.
            </p>
            <h3 style={styles.subtitle}>Order Cancellations</h3>
            <p style={styles.paragraph}>
              You can cancel your order at any time before it enters the "In Transit" milestone. Click the 
              <strong>"Cancel Order"</strong> button in your Orders history. Any redeemed coins will be immediately 
              refunded to your wallet, and payment refunds will be processed within 5-7 business days.
            </p>
            <h3 style={styles.subtitle}>🚚 Shipping & Delivery Policy</h3>
            <p style={styles.paragraph}>
              Orders are dispatched within 24 hours of successful placement. Express 1-Day home delivery is available 
              for all addresses located within the Bengaluru hub zone. Shipping to other national zones takes 
              between 3-5 business days. We offer free standard shipping on orders valued above ₹500.
            </p>
          </div>
        );
      case 'contact':
      default:
        return (
          <div>
            <h2 className="info-title">Contact Support &amp; Partnerships</h2>
            <p className="info-paragraph">
              Need assistance with an order, payment transaction, or creator payout? Get in touch with our team directly.
            </p>
            

            <div className="info-contact-card">
              <div className="info-contact-item">
                <Building size={20} color="var(--primary-color)" style={{ flexShrink: 0 }} />
                <div>
                  <strong>Registered Office Address:</strong><br />
                  AbKharido Retail Private Limited,<br />
                  Outer Ring Road, Devarabeesanahalli Village,<br />
                  Bengaluru, Karnataka - 560103, India.
                </div>
              </div>
              <div className="info-contact-item">
                <Mail size={20} color="var(--primary-color)" style={{ flexShrink: 0 }} />
                <div>
                  <strong>Support Helpdesk:</strong><br />
                  <a href="mailto:help@abkharido.com" style={{ color: 'var(--primary-color)', fontWeight: 'bold' }}>help@abkharido.com</a>
                </div>
              </div>
              <div className="info-contact-item">
                <FileText size={20} color="var(--primary-color)" style={{ flexShrink: 0 }} />
                <div>
                  <strong>Corporate Identification Number (CIN):</strong><br />
                  U72900KA2026PTC998877
                </div>
              </div>
            </div>

            <h3 className="info-subtitle">🤝 Creator &amp; Affiliate Partnership Dashboard</h3>
            <p className="info-paragraph">
              Are you looking to view your share stats, withdraw cash commissions, or track your friend referral progress? 
              You can access all creator tools directly inside the <strong>Affiliate / Creator Tab</strong> in the top header.
            </p>
          </div>
        );
    }
  };

  return (
    <div className="container info-page-wrap animate-fade-in">
      <div className="info-sidebar">
        <h3 className="info-sidebar-title">Policies &amp; Info</h3>
        <div className="info-nav-menu">
          <a href="#about" className="info-nav-link">🏢 About AbKharido</a>
          <a href="#terms" className="info-nav-link">📄 Terms of Use</a>
          <a href="#privacy" className="info-nav-link">🔒 Privacy Policy</a>
          <a href="#returns" className="info-nav-link">↩️ Returns &amp; Refund</a>
          <a href="#contact" className="info-nav-link">📞 Contact Support</a>
        </div>
      </div>
      <div className="card info-content-card">
        {renderContent()}
      </div>
    </div>
  );
};

const styles = {
  pageContainer: {
    padding: '24px 0',
    display: 'flex',
    gap: '24px',
    maxWidth: '1000px',
    minHeight: '60vh',
    flexWrap: 'wrap'
  },
  sidebar: {
    width: '240px',
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    border: '1px solid var(--border-light)',
    borderRadius: '4px',
    padding: '16px',
    minWidth: '220px',
    flex: '1 0 220px'
  },
  sidebarTitle: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: 'var(--text-primary)',
    borderBottom: '1px solid #eaeaea',
    paddingBottom: '10px',
    marginBottom: '12px'
  },
  navMenu: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px'
  },
  sidebarLink: {
    fontSize: '13px',
    color: 'var(--text-primary)',
    fontWeight: '500',
    transition: 'color 0.15s'
  },
  contentCard: {
    flex: '3 0 450px',
    padding: '32px',
    backgroundColor: '#ffffff'
  },
  title: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#212121',
    borderBottom: '1px solid #eaeaea',
    paddingBottom: '12px',
    marginBottom: '20px'
  },
  subtitle: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: '#212121',
    marginTop: '20px',
    marginBottom: '8px'
  },
  date: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
    marginBottom: '16px',
    fontStyle: 'italic'
  },
  paragraph: {
    fontSize: '13px',
    color: '#424242',
    lineHeight: '1.6',
    marginBottom: '14px'
  },
  contactCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    marginTop: '20px',
    backgroundColor: '#fafafa',
    border: '1px solid #e0e0e0',
    borderRadius: '4px',
    padding: '20px'
  },
  contactItem: {
    display: 'flex',
    gap: '12px',
    fontSize: '13px',
    color: '#212121',
    lineHeight: '1.5'
  }
};

export default InfoPage;
